[tool.poetry]
name = "pyramm"
version = "1.6"
description = "Provides a wrapper to the RAMM API and additional tools for positional referencing"
authors = ["John Bull"]
homepage = "https://github.com/johnbullnz/pyramm"
license = "MIT"
readme = "README.md"
keywords = ["CAPTIF", "RAMM"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.25.0"
pandas = "^1.1.4"
geopandas = "^0.8.1"
numpy = "^1.19.4"
Shapely = "^1.7.1"
scipy = "^1.5.4"
pyproj = "^3.0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
pytest-randomly = "^3.5.0"
pre-commit = "^2.9.2"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
